### ISSUE TITLE
mein を main に修正

### ISSUE THREAD

**Issue by totsumaru** [morimotoyuuki111/Go2#2]
https://github.com/morimotoyuuki111/Go2/blob/60d793e80f1907dd7a55e24f9d5a7faa98a44c07/Exported%20names.md?plain=1#L19

mainの表記がよくmeinになっています。
これで慣れてしまうと間違っていることに気付かず、プログラムが動かない原因にもなるので、今後意識しましょう！
※ 29行目もmeinになっています。

**Comment by morimotoyuuki111** [comment]
ありがとうございます。
意識不足が招いたことなのでプログラムを書く前、書いた後に違いがないか確認していきます。

**Comment by morimotoyuuki111** [comment]
ありがとうございます。意識不足が招いたことなのでプログラムを書く前、書いた後確認をして進めていきます。
